[package]
name = "ragit-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
sha3 = "0.10"
thiserror = "1.0"
serde_json = "1.0"
ragit-fs = { path = "../fs" }
flate2 = "1.0"
regex = "1.10.4"
image = "0.25.1"
