[package]
name = "ragit"
version = "0.4.2"
edition = "2024"
license = "MIT"
description = "git-like rag pipeline"
repository = "https://github.com/baehyunsol/ragit"
documentation = "https://docs.rs/ragit"

[[bin]]
name = "rag"
path = "src/main.rs"

[workspace]
members = [
    "crates/api",
    "crates/cli",
    "crates/fs",
    "crates/ignore",
    "crates/korean",
    "crates/pdl",
    "crates/server",
    "crates/ragit-utils",
    "crates/ragit-schema",
]

[dependencies]
async-recursion = "1.1.1"
chrono = "0.4.40"
csv = { version = "1.3.1", optional = true }
flate2 = "1.1.0"
image = { version = "0.25.5", default-features = false, features = ["rayon", "bmp", "dds", "exr", "ff", "gif", "hdr", "ico", "jpeg", "png", "pnm", "qoi", "tga", "tiff", "webp"] }
lazy_static = "1.5.0"
mupdf = { version = "0.5.0", optional = true }
png = { version = "0.17.16", optional = true }  # `resvg`'s function returns `png::EncodingError`
ragit-api = { path = "./crates/api", version = "0.4.2" }
ragit-cli = { path = "./crates/cli", version = "0.4.2" }
ragit-fs = { path = "./crates/fs", version = "0.4.2", features = ["diff"] }
ragit-ignore = { path = "./crates/ignore", version = "0.4.2" }
ragit-korean = { path = "./crates/korean", version = "0.4.2", optional = true }
ragit-pdl = { path = "./crates/pdl", version = "0.4.2" }
ragit-utils = { path = "./crates/ragit-utils", version = "0.1.0" }
ragit-schema = { path = "./crates/ragit-schema", version = "0.1.0" }
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["multipart"] }
resvg = { version = "0.45.1", optional = true }
rust-stemmers = "1.2.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = { version = "1.0.139", features = ["arbitrary_precision"] }
sha3 = "0.10.8"
strum = { version = "0.26", features = ["derive"] }
tera = "1.20.0"
tokio = { version = "1.43.0", features = ["full"] }
url = "2.5.4"
zstd = "0.13.3"

[features]
# `csv` is small enough and is purely in Rust.
default = ["csv"]
full = ["csv", "korean"]

csv = ["dep:csv"]
korean = ["dep:ragit-korean"]
pdf = ["dep:mupdf"]
svg = ["dep:resvg", "dep:png"]

# This feature only affects `rag version --build-options`.
# Please make sure to enable this when you build ragit with "production" profile.
production = []

[profile.production]
inherits = "release"
codegen-units = 1
lto = "fat"

# mupdf does not compile without this patch on MacOS
[patch.crates-io]
pathfinder_simd = { git = "https://github.com/servo/pathfinder.git" }
