[package]
name = "ragit-ignore"
version = "0.3.5"
edition = "2024"
license = "MIT"
description = "ignore-parser for ragit"

[dependencies]
regex = "1.11.1"
ragit-fs = { path = "../fs", version = "0.3.5" }
