[package]
name = "ragit-index-save-to-file"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../ragit-types" }
ragit-index = { path = "../ragit-index" }
ragit-fs = { path = "../fs" }
anyhow = "1.0"
serde_json = "1.0"