[package]
name = "ragit-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-utils = { path = "../ragit-utils" }
ragit-fs = { path = "../fs" }
ragit-pdl = { path = "../pdl" }
ragit-uid = { path = "../ragit-uid" }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.141"
anyhow = "1.0.98"
