[package]
name = "ragit-muse-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
ragit-types = { path = "../ragit-types" }
ragit-index-types = { path = "../ragit-index-types" }
ragit-model = { path = "../ragit-model" }
ragit-muse = { path = "../ragit-muse" }
anyhow = "1.0"
