[package]
name = "ragit-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
sha3 = "0.10.8"
chrono = "0.4.40"
ragit-fs = { path = "../fs", version = "0.4.2" }
