[package]
name = "ragit-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ragit-utils = { path = "../ragit-utils" }
ragit-fs = { path = "../fs" }
serde_json = "1.0"
